spring:
  config:
    activate:
      on-profile: dev
  security:
    user:
      name: user
      password: 1111

  datasource:
    url: "jdbc:mysql://localhost:13306/hhplusdev"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: user_password

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 50000

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
    admin:
      auto-create: true
