server:
  servlet:
    encoding:
      force-response: true

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: "jdbc:mysql://localhost:13306/hhplusdev"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: false
